name: Theory Group
url: http://theory.cs.umass.edu

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: adjunct
    name: Visiting and Adjunct Faculty
  - key: postdoc
    name: Postdocs
  - key: grad
    name: Graduate Students
  - key: alum
    name: Theory Group Alumni

# Number of news stories on the front page.
front_page_news: 0

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Seminar
    link: /seminar
  - title: Theory Day
    link: /theory-day
  # - title: Publications
  #   link: /publications.html
  # - title: Code
  #   link: /code.html
